"""empty message

Revision ID: 71e9dfbc0716
Revises: 4769a8dc3eb4
Create Date: 2019-03-14 15:58:03.684219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e9dfbc0716'
down_revision = '4769a8dc3eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_strings_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_string_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_string_id'], ['qr_strings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_strings_errors')
    # ### end Alembic commands ###
